[988] Add support for a post selection
eclipse-sirius/sirius-components pull request #1020
Opened 2022-01-26 15:01 UTC by AxelRICHARD

### Type of this PR 

- [x] New feature or improvement

### Issue(s)

https://github.com/eclipse-sirius/sirius-components/issues/988

### What does this PR do?

Introduce new concepts: WorkbenchSelection and WorkbenchSelectionEntry.
The Success of an operation can now contains a new parameter named
'newSelection' and containing a WorkbenchSelection.

2022-01-31 08:26 UTC, pcdavid reviewed
Any particular reason to only handle NodeTools?

2022-01-31 10:18 UTC, AxelRICHARD commented
No reason, I will amend the commit to also handle Edges.

2022-02-02 13:21 UTC, sbegaudeau requested changes
I'll take over the PR to make the required changes and merge it on master

2022-02-02 13:21 UTC, sbegaudeau commented on backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
> +  newSelection: WorkbenchSelection!
The GraphQL schema of the `InvokeEdgeToolOnDiagramSuccessPayload` should be updated too (I'll do it)

2022-02-02 13:21 UTC, sbegaudeau commented on backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/WorkbenchSelection.java
> +public class WorkbenchSelection {
I'll add a `toString()` here

2022-02-02 13:21 UTC, sbegaudeau commented on backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/WorkbenchSelectionEntry.java
> +public class WorkbenchSelectionEntry {
I'll add a `toString()` here too

2022-02-02 13:21 UTC, sbegaudeau commented on frontend/src/diagram/DiagramWebSocketContainer.tsx
> +      const newSelection = invokeNodeToolOnDiagram?.newSelection;
`invokeNodeToolOnDiagram` cannot be `null` unless I am mistaken, same for `invokeEdgeToolOnDiagram`. In a similar fashion, `entries` cannot be `null` so no need for `?.` The typing should indicate that.

2022-02-02 13:34 UTC, sbegaudeau commented on backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
> +  newSelection: WorkbenchSelection!
Done

2022-02-03 09:48 UTC, sbegaudeau commented on frontend/src/diagram/DiagramWebSocketContainer.tsx
> +      const newSelection = invokeNodeToolOnDiagram?.newSelection;
I have added the necessary TypeScript typing for all the code manipulated in this PR.

2022-02-03 09:49 UTC, sbegaudeau approved these changes

2022-02-03 09:55 UTC, merged