[cleanup] Use the representation kind to compute the representation image
eclipse-sirius/sirius-components pull request #1040
Opened 2022-02-06 14:48 UTC by sbegaudeau

Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

2022-02-06 14:50 UTC, sbegaudeau commented
This very small change will be necessary in order to compute the representation image from either a `RepresentationMetadata` or an `IRepresentation`

2022-02-07 14:29 UTC, gcoutable approved these changes

2022-02-07 15:55 UTC, gcoutable requested changes
I think the changelog should be updated

2022-02-07 16:52 UTC, gcoutable approved these changes

2022-02-07 20:33 UTC, merged