[105] Take Domain class into account for DomainBasedEdges conversion
eclipse-sirius/sirius-components pull request #106
Opened 2020-11-13 15:10 UTC by AxelRICHARD

Signed-off-by: Axel RICHARD <axel.richard@obeo.fr>

2020-11-24 14:01 UTC, pcdavid requested changes

2020-11-24 14:01 UTC, pcdavid commented on backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java
> +            String domainClass = edgeMapping.getDomainClass();
`DomainClassPredicate` (which is used underneath) already handles the case where the domain class is blank as equivalent to `EObject`. It just does not accept `null`. Proposal
```java
String domainClass = Optional.ofNullable(edgeMapping.getDomainClass()).orElse("");
```
and let `DomainClassPredicate` treat "" as "anything".

2020-11-30 10:17 UTC, sbegaudeau commented
It looks good on my side, I'll ping @pcdavid to see if it's ok for him too

2020-11-30 10:23 UTC, sbegaudeau approved these changes

2020-11-30 10:38 UTC, pcdavid approved these changes

2020-11-30 10:38 UTC, merged