[1102] Fix the list item label positioning
eclipse-sirius/sirius-components pull request #1108
Opened 2022-03-15 11:18 UTC by lfasani

Add the 'label:inside-begin' label type.
Update the front and the ELK layout

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1102
Signed-off-by: Laurent Fasani <laurent.fasani@obeo.fr>

### Type of this PR 

- [X] Bug fix

### How to test this PR?

- [ ] Frontend Unit tests
- [ ] Backend Unit tests
- [ ] Cypress : please specify
- [X] Manual Test :
-Diagram Edition - Support List containers

2022-03-16 09:14 UTC, sbegaudeau requested changes
https://user-images.githubusercontent.com/422587/158556222-759335b1-09fd-4db1-944b-4649d517ab4f.mov

It's better for the incremental layout but worse for the ELK layout... Have you tested your solution?

2022-03-25 15:57 UTC, lfasani commented on backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/ImageRegistry.java
> -
This part has fixed https://github.com/eclipse-sirius/sirius-components/issues/1106 in addtion to the label icon display
I am sorry I can not remember the use case where this code was useful

2022-03-28 15:10 UTC, sbegaudeau reviewed
I'll update the PR with the minor fixed required

2022-03-28 15:10 UTC, sbegaudeau commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-components/issues/1104[#1102] [diagram] Fix the node label positioning (rectangle, list and list item)
The URL is not valid, which is why the build is failing. Please keep an eye on the results of the build of your pull requests

2022-03-28 15:10 UTC, sbegaudeau commented on backend/sirius-components-starter/src/main/java/org/eclipse/sirius/components/starter/configurationproperties/RefererConfigurationProperty.java
> +    }
No need for two getter for the same variable

2022-03-28 15:36 UTC, sbegaudeau approved these changes

2022-03-28 15:39 UTC, merged