[doc] Add some documentation in order to start integrating Sirius Components
eclipse-sirius/sirius-components pull request #1135
Opened 2022-04-04 13:55 UTC by sbegaudeau

Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

2022-04-06 08:03 UTC, gcoutable requested changes

2022-04-06 08:03 UTC, gcoutable commented on doc/reference/reference.adoc
> +The only required part of the schema is located in `sirius-components-collaborative/src/main/resources/schema/code.graphqls`.
`core.graphqls`

2022-04-06 08:03 UTC, gcoutable commented on doc/reference/reference.adoc
> +This file contains the code concepts of our GraphQL schema and is required by all the other schema files.
the _core_ concepts of ...

2022-04-08 06:15 UTC, sbegaudeau commented on doc/reference/reference.adoc
> +The only required part of the schema is located in `sirius-components-collaborative/src/main/resources/schema/code.graphqls`.
Done

2022-04-08 06:15 UTC, sbegaudeau commented on doc/reference/reference.adoc
> +This file contains the code concepts of our GraphQL schema and is required by all the other schema files.
Done

2022-04-08 07:21 UTC, gcoutable approved these changes

2022-04-08 07:32 UTC, merged