[1154] Display the palette where the click has been made
eclipse-sirius/sirius-components pull request #1156
Opened 2022-04-12 14:14 UTC by gcoutable

### Type of this PR 

- [x] Bug fix
- [ ] New feature or improvement
- [ ] Documentation
- [ ] Cleanup
- [ ] Test
- [ ] Build/Releng

### Issue(s)

closes https://github.com/eclipse-sirius/sirius-components/issues/1154

### What does this PR do?

This PR takes the position of the mouse when the click is made, then this position is given to the action that will display the contextual palette.

### How to test this PR?

- [ ] Frontend Unit tests
- [ ] Backend Unit tests
- [ ] Cypress : please specify
- [x] Manual Test: See the "step to reproduce" described in the issue. The actual behavior should not happen.

2022-04-12 14:29 UTC, sbegaudeau requested changes

2022-04-12 14:29 UTC, sbegaudeau commented on frontend/src/diagram/sprotty/DiagramServer.types.ts
> +  kind: typeof ShowContextualToolbarAction.KIND;
Why `typeof`?

2022-04-14 15:32 UTC, gcoutable commented on frontend/src/diagram/sprotty/DiagramServer.types.ts
> +export namespace ShowContextualToolbarAction {
I'll remove the _namespace_ declaration and will use a simpler way to declare the action.

2022-04-20 08:16 UTC, sbegaudeau approved these changes

2022-04-20 08:21 UTC, merged