[cleanup] Add the same trigger between push/PR
eclipse-sirius/sirius-components pull request #167
Opened 2020-12-07 09:20 UTC by hmarchadour

### Type of this PR 

- [ ] Bug fix
- [ ] New feature or improvement
- [ ] Documentation
- [x ] Cleanup
- [ ] Test
- [ ] Build/Releng

2020-12-07 09:22 UTC, sbegaudeau requested changes
The build will change soon, probably even today. This improvement should be made on top of the new build (and then include the sample folder).

2020-12-07 09:24 UTC, sbegaudeau commented
And of course, if should include the `.github/workflows` folder too

2020-12-07 09:44 UTC, hmarchadour commented
> And of course, if should include the `.github/workflows` folder too

Done

2020-12-18 14:03 UTC, sbegaudeau approved these changes

2020-12-18 14:03 UTC, merged