[2288] Make IconLabel a react flow node
eclipse-sirius/sirius-components pull request #2305
Opened 2023-08-23 15:32 UTC by gcoutable

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-09-04 11:50 UTC, mcharfadi requested changes

2023-09-04 11:50 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
> +            x: 0,
I think it would look better with a padding instead of 0 in at the x position

2023-09-04 12:51 UTC, mcharfadi reviewed
Maybe we could precise the node.extent to avoid the node being moved at the same position as the label of the parent node.

2023-09-11 09:10 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
> +            x: 0,
Done

2023-09-11 13:30 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
> +            x: 0,
After trying to implement compartments, the child x position for list nodes must be 0 otherwise padding is visible between a node and its compartment children.
I will add a margin to IconLabels instead.

2023-09-18 08:16 UTC, gcoutable commented
> Maybe we could precise the node.extent to avoid the node being moved at the same position as the label of the parent node.

With https://github.com/eclipse-sirius/sirius-web/issues/288 node will be able to move anywhere, so, I think the `node.extent` will not be used at all

2023-09-18 09:06 UTC, mcharfadi commented
I'm not able to hide the nodes, if we can't hide them we should not have the action in the toolbar.

2023-09-18 13:29 UTC, mcharfadi approved these changes

2023-09-18 13:36 UTC, mcharfadi requested changes
There is a small issue regarding layout when hiding all the IconLabel of a node
https://github.com/eclipse-sirius/sirius-web/assets/121878084/446a8af6-27c3-4b42-a528-8ce8467d6001

2023-09-18 14:02 UTC, gcoutable commented
> There is a small issue regarding layout when hiding all the IconLabel of a node https://github.com/eclipse-sirius/sirius-web/assets/121878084/446a8af6-27c3-4b42-a528-8ce8467d6001

A fix to that issue is included in the next [PR](https://github.com/eclipse-sirius/sirius-web/pull/2315).
We may merge the next PR (which can include this one) directly

2023-10-10 16:01 UTC, gcoutable commented
I am closing this PR because it includes layout regressions that have been fixed in the next PR (https://github.com/eclipse-sirius/sirius-web/pull/2315), and https://github.com/eclipse-sirius/sirius-web/pull/2315 includes the commit from this PR.
I have done that to prevent the staging instance from having a state with an issue.

2023-10-10 16:01 UTC, closed without merging