Improve View meta-model with features that are already supported in our diagrams
eclipse-sirius/sirius-components pull request #644
Opened 2021-07-21 09:31 UTC by gcoutable

### Type of this PR 

- [ ] Bug fix
- [x] New feature or improvement
- [ ] Documentation
- [ ] Cleanup
- [ ] Test
- [ ] Build/Releng

### Issue(s)

https://github.com/eclipse-sirius/sirius-components/issues/598
https://github.com/eclipse-sirius/sirius-components/issues/599
https://github.com/eclipse-sirius/sirius-components/issues/600

### What does this PR do?

This PR adds the following features to the View meta-models:
- node border size
- edge width
- font formats for node label
- node label color

2021-07-22 13:09 UTC, pcdavid commented on backend/sirius-web-view/src/main/resources/model/view.ecore
> +    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderSize" lowerBound="1"
Actually, I thought the core of Sirius Web already supported dynamic border sizes and it was just a matter of passing the expression, but I was wrong. We can not do better in the View DSL itself, the core would need to change to support that and it's out of scope of this PR.

2021-07-22 13:09 UTC, pcdavid commented on backend/sirius-web-view/src/main/resources/model/view.ecore
> +    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeWidth" lowerBound="1"
Same remark as above for my other comment.

2021-07-22 13:09 UTC, pcdavid approved these changes

2021-07-22 13:11 UTC, sbegaudeau requested changes
Just to wait for the cool down, I'll have to review the impact of the separation of the business layer first.

2021-08-10 14:24 UTC, sbegaudeau approved these changes
(waiting for the build to merge)

2021-08-10 14:45 UTC, merged