Improve warnings for Java extension loading errors
eclipse-sirius/sirius-components pull request #718
Opened 2021-08-28 22:20 UTC by berezovskyi

### Type of this PR 

- [ ] Bug fix
- [ ] New feature or improvement
- [ ] Documentation
- [x] Cleanup
- [ ] Test
- [ ] Build/Releng

### Issue(s)

...

### What does this PR do?

- Use a plain warning message when a class cannot be loaded
- Do not try to load a class when the extension uses ::-style reference (@pcdavid told me that there is no plan to support such references in SiriusW)

### Screenshot/screencast of this PR

...
 

### Potential side effects

...

### How to test this PR?

- [ ] Frontend Unit tests
- [ ] Backend Unit tests
- [ ] Cypress : please specify
- [x] Manual Test : log messages don't need automated tests?

### Checklist

- [x] I have read CONTRIBUTING carefully.
- [x] I have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [x] All my commits are signed-off (`-s`) with my mail address of my Eclipse Account.
- [ ] I have covered my changes by unit tests or integration tests or manual tests.
- [x] All tests pass.
- [ ] I have updated the documentation accordingly
- [ ] New React components are availables in storybook

2021-08-28 23:06 UTC, berezovskyi commented
Sample messages:

> WARN 63954 --- [           main] o.e.s.w.e.c.AQLInterpreterFactory        : Sirius Web does not support Accelleo-style :: references
> ERROR 63954 --- [           main] o.e.s.w.e.c.AQLInterpreterFactory        : Could not load class 'org.eclipse.lyo.tools.codegenerator.ui.popupMenus.AcceleoGenerateCodegeneratorAction'; not all dependencies could be instantiated by the JVM: org/eclipse/ui/IActionDelegate

2021-08-30 08:06 UTC, pcdavid requested changes

2021-08-30 08:06 UTC, pcdavid commented on backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/AQLInterpreterFactory.java
> +                this.logger.warn("Sirius Web does not support Accelleo-style :: references");
Typo: "Acceleo" has a single "l"

2021-08-31 07:06 UTC, pcdavid commented on backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/AQLInterpreterFactory.java
> +                this.logger.warn("Sirius Web does not support Accelleo-style :: references");
Also, I just noticed the newly added strings are missing the NON-NLS markers. This is normally configured to cause compilation errors. Are you developing inside STS, or some other IDE?

One final note (I think): could you prefix your commit messages with `[cleanup] `?

2021-09-04 20:41 UTC, berezovskyi commented
@pcdavid fixed all your comments, please check. Regarding NON-NLS, I used STS but disabled those errors as it lit up my codebase with way too many errors after IntelliJ. I brought the level back to error in my sirius-components config.

2021-09-20 08:42 UTC, pcdavid approved these changes

2021-09-20 08:42 UTC, merged

2021-09-20 08:43 UTC, pcdavid commented
Thanks for the contribution, and sorry for the delay.