[fix] Handle invalid format more gracefully when editing numeric properties
eclipse-sirius/sirius-components pull request #812
Opened 2021-11-03 14:39 UTC by pcdavid

Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

### Type of this PR 

- [ ] Bug fix
- [ ] New feature or improvement
- [ ] Documentation
- [ ] Cleanup
- [ ] Test
- [ ] Build/Releng

### Issue(s)

...

### What does this PR do?

...

### Screenshot/screencast of this PR

...
 

### Potential side effects

...

### How to test this PR?

- [ ] Frontend Unit tests
- [ ] Backend Unit tests
- [ ] Cypress : please specify
- [ ] Manual Test : please specify

### Checklist

- [ ] I have read CONTRIBUTING carefully.
- [ ] I have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [ ] All my commits are signed-off (`-s`) with my mail address of my Eclipse Account.
- [ ] I have covered my changes by unit tests or integration tests or manual tests.
- [ ] All tests pass.
- [ ] I have updated the documentation accordingly
- [ ] New React components are availables in storybook

2021-11-03 15:15 UTC, sbegaudeau requested changes

2021-11-03 15:15 UTC, sbegaudeau commented on backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/NumberIfDescriptionProvider.java
> +                    result = new Failure(MessageFormat.format("The new value ''{0}'' is not a valid number", newValue)); //$NON-NLS-1$
Use the message service to allow support for internationalization

2021-11-25 08:41 UTC, pcdavid commented
Also propagate the specific error message (if any) to the frontend.

Uploading Screencast_25-11-2021_09:39:56.mp4…

2021-12-08 10:18 UTC, sbegaudeau approved these changes

2021-12-08 10:18 UTC, sbegaudeau commented
Waiting for the build to complete to merge

2021-12-08 10:23 UTC, merged