sbe/enh/graphical selection
eclipse-sirius/sirius-components pull request #918
Opened 2022-01-05 14:31 UTC by sbegaudeau

- [914] Extract the DiagramMouseListener and improve its typing
- [914] Add the graphical selection for nodes and edges

2022-01-07 15:26 UTC, gcoutable requested changes

2022-01-07 15:26 UTC, gcoutable commented on frontend/src/diagram/DiagramWebSocketContainer.tsx
> +        const type = selectedElement instanceof Node ? 'Node' : 'Edge';
Looking inside the state, the selected graphical element is always an `Edge` like if _selectedElement_ was never a `Node`

2022-01-07 17:41 UTC, gcoutable approved these changes

2022-01-10 12:51 UTC, sbegaudeau commented
I'll perform some additional manual tests to help ensure that the rebase has not broken anything.

2022-01-10 16:13 UTC, merged