[952] The contextual palette can use many lines to display its tools
eclipse-sirius/sirius-components pull request #954
Opened 2022-01-12 15:00 UTC by gcoutable

### Type of this PR 

- [ ] Bug fix
- [x] New feature or improvement
- [ ] Documentation
- [ ] Cleanup
- [ ] Test
- [ ] Build/Releng

### Issue(s)

https://github.com/eclipse-sirius/sirius-components/issues/952

### What does this PR do?

This PR prevents the contextual palette to be too long by displaying tools on many lines if needed.

2022-01-14 07:42 UTC, pcdavid commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-components/issues/952[#952] [diagram] The contextual palette can be displayed with many lines
It doesn't seem precise enough. I *can*, but when/why? Proposal:

> When there are more than 15 tools to display, the contextual palette is split in multiple lines.

2022-01-17 10:30 UTC, sbegaudeau commented
Could you rebase this PR please, it will be easier for you to preserve your changes while handling the conflict

2022-01-18 08:45 UTC, sbegaudeau commented
I have an issue related to keys with your PR:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ContextualPalette`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at ContextualPalette (http://localhost:3000/static/js/vendors~main.chunk.js:23912:35)
    at div
    at div
    at div
    at DropArea (http://localhost:3000/static/js/vendors~main.chunk.js:19553:32)
    at div
```

I still don't know how to reproduce it all the time

2022-01-18 08:46 UTC, sbegaudeau commented on frontend/src/diagram/palette/ContextualPalette.tsx
> +    if (!!invokeLabelEdit) {
Why all those `!!`? Why not `if(invokeLabelEdit)`?

2022-01-18 08:47 UTC, sbegaudeau requested changes

2022-01-18 08:47 UTC, sbegaudeau commented on frontend/src/diagram/palette/ContextualPalette.tsx
> +    while (!!toolSectionsContent && toolSectionsContent.length > 0) {
Can toolSectionsContent even be `null` or `undefined` here?

2022-01-18 09:05 UTC, sbegaudeau commented
<img width="1093" alt="Capture d’écran 2022-01-18 à 09 58 50" src="https://user-images.githubusercontent.com/422587/149905044-c52d7ca9-9ebe-4e36-93f4-13f435957d2f.png">


- I don't have 15 tools per line
- The hardcoded tools do not appear on the first line
- All the tools do not have the same dimension
- The icons are not centered

Personally, I don't really care about this constraint that the hardcoded tools should appear on the first line, It does not make a lot of sense and makes the code really complex for no real benefit. I think we would be way better with a plain simple CSS grid with no magic ordering what so ever.

2022-01-19 13:23 UTC, merged